#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Dictionary of standard Quranic translations for missing 334 lemmas."""

MISSING_TRANSLATIONS = {
    "QCV-0022": {
        "lemma_ar": "عَن",
        "root": "",
        "pos": "P",
        "word_type": "particle",
        "freq": 465,
    },
    "QCV-0024": {
        "lemma_ar": "ءَامَنَ",
        "root": "ا م ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 537,
    },
    "QCV-0033": {
        "lemma_ar": "رَءَا",
        "root": "ر ا ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 271,
    },
    "QCV-0040": {
        "lemma_ar": "قَوْم",
        "root": "ق و م",
        "pos": "N",
        "word_type": "noun",
        "freq": 383,
    },
    "QCV-0045": {
        "lemma_ar": "عَذَاب",
        "root": "ع ذ ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 322,
    },
    "QCV-0048": {
        "lemma_ar": "ءَايَة",
        "root": "ا ي ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 382,
    },
    "QCV-0049": {
        "lemma_ar": "شَآءَ",
        "root": "ش ي ا",
        "pos": "V",
        "word_type": "verb",
        "freq": 236,
    },
    "QCV-0050": {
        "lemma_ar": "شَىْء",
        "root": "ش ي ا",
        "pos": "N",
        "word_type": "noun",
        "freq": 283,
    },
    "QCV-0056": {
        "lemma_ar": "كِتَٰب",
        "root": "ك ت ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 260,
    },
    "QCV-0061": {
        "lemma_ar": "اتَّقَىٰ",
        "root": "و ق ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 166,
    },
    "QCV-0063": {
        "lemma_ar": "أَىّ",
        "root": "",
        "pos": "INTG",
        "word_type": "particle",
        "freq": 60,
    },
    "QCV-0107": {
        "lemma_ar": "أَرَادَ",
        "root": "ر و د",
        "pos": "V",
        "word_type": "verb",
        "freq": 139,
    },
    "QCV-0112": {
        "lemma_ar": "سَبِيل",
        "root": "س ب ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 176,
    },
    "QCV-0113": {
        "lemma_ar": "كَٰفِرُون",
        "root": "ك ف ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 129,
    },
    "QCV-0114": {
        "lemma_ar": "اتَّخَذَ",
        "root": "ا خ ذ",
        "pos": "V",
        "word_type": "verb",
        "freq": 124,
    },
    "QCV-0125": {
        "lemma_ar": "لَمَّا",
        "root": "",
        "pos": "T",
        "word_type": "noun",
        "freq": 156,
    },
    "QCV-0141": {
        "lemma_ar": "أَهْل",
        "root": "ا ه ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 127,
    },
    "QCV-0145": {
        "lemma_ar": "مُوسَىٰ",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 136,
    },
    "QCV-0147": {
        "lemma_ar": "تَوَلَّىٰ",
        "root": "و ل ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 78,
    },
    "QCV-0149": {
        "lemma_ar": "لَيْسَ",
        "root": "ل ي س",
        "pos": "V",
        "word_type": "verb",
        "freq": 89,
    },
    "QCV-0152": {
        "lemma_ar": "جَزَىٰ",
        "root": "ج ز ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 73,
    },
    "QCV-0155": {
        "lemma_ar": "أَجْر",
        "root": "ا ج ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 105,
    },
    "QCV-0159": {
        "lemma_ar": "أَلْقَىٰٓ",
        "root": "ل ق ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 71,
    },
    "QCV-0160": {
        "lemma_ar": "جَرَيْ",
        "root": "ج ر ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 57,
    },
    "QCV-0161": {
        "lemma_ar": "أَقَامَ",
        "root": "ق و م",
        "pos": "V",
        "word_type": "verb",
        "freq": 54,
    },
    "QCV-0162": {
        "lemma_ar": "قَوْل",
        "root": "ق و ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 92,
    },
    "QCV-0164": {
        "lemma_ar": "ذُو",
        "root": "",
        "pos": "N",
        "word_type": "noun",
        "freq": 93,
    },
    "QCV-0184": {
        "lemma_ar": "مَاذَا",
        "root": "",
        "pos": "INTG",
        "word_type": "particle",
        "freq": 26,
    },
    "QCV-0187": {
        "lemma_ar": "كَم",
        "root": "",
        "pos": "INTG",
        "word_type": "particle",
        "freq": 21,
    },
    "QCV-0202": {
        "lemma_ar": "دِين",
        "root": "د ي ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 92,
    },
    "QCV-0205": {
        "lemma_ar": "إِنسَٰن",
        "root": "ا ن س",
        "pos": "N",
        "word_type": "noun",
        "freq": 71,
    },
    "QCV-0206": {
        "lemma_ar": "أَحْبَبْ",
        "root": "ح ب ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 64,
    },
    "QCV-0207": {
        "lemma_ar": "تَلَىٰ",
        "root": "ت ل و",
        "pos": "V",
        "word_type": "verb",
        "freq": 61,
    },
    "QCV-0209": {
        "lemma_ar": "حَيَوٰة",
        "root": "ح ي ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 76,
    },
    "QCV-0210": {
        "lemma_ar": "قِيَٰمَة",
        "root": "ق و م",
        "pos": "N",
        "word_type": "noun",
        "freq": 70,
    },
    "QCV-0212": {
        "lemma_ar": "مَال",
        "root": "م و ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 86,
    },
    "QCV-0213": {
        "lemma_ar": "أَنفَقَ",
        "root": "ن ف ق",
        "pos": "V",
        "word_type": "verb",
        "freq": 68,
    },
    "QCV-0214": {
        "lemma_ar": "شَيْطَٰن",
        "root": "ش ط ن",
        "pos": "PN",
        "word_type": "noun",
        "freq": 88,
    },
    "QCV-0220": {
        "lemma_ar": "أَلِيم",
        "root": "ا ل م",
        "pos": "ADJ",
        "word_type": "adjective",
        "freq": 72,
    },
    "QCV-0223": {
        "lemma_ar": "أَصْحَٰب",
        "root": "ص ح ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 78,
    },
    "QCV-0224": {
        "lemma_ar": "أَصَابَ",
        "root": "ص و ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 64,
    },
    "QCV-0225": {
        "lemma_ar": "قَضَىٰٓ",
        "root": "ق ض ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 59,
    },
    "QCV-0230": {
        "lemma_ar": "قُرْءَان",
        "root": "ق ر ا",
        "pos": "PN",
        "word_type": "noun",
        "freq": 70,
    },
    "QCV-0231": {
        "lemma_ar": "صَلَوٰة",
        "root": "ص ل و",
        "pos": "N",
        "word_type": "noun",
        "freq": 83,
    },
    "QCV-0234": {
        "lemma_ar": "عَٰلَمِين",
        "root": "ع ل م",
        "pos": "N",
        "word_type": "noun",
        "freq": 73,
    },
    "QCV-0238": {
        "lemma_ar": "اسْتَكْبَرَ",
        "root": "ك ب ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 40,
    },
    "QCV-0240": {
        "lemma_ar": "يَوْمَئِذ",
        "root": "",
        "pos": "T",
        "word_type": "noun",
        "freq": 70,
    },
    "QCV-0241": {
        "lemma_ar": "مَسَّ",
        "root": "م س س",
        "pos": "V",
        "word_type": "verb",
        "freq": 56,
    },
    "QCV-0244": {
        "lemma_ar": "قَلِيل",
        "root": "ق ل ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 70,
    },
    "QCV-0247": {
        "lemma_ar": "فَضْل",
        "root": "ف ض ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 84,
    },
    "QCV-0249": {
        "lemma_ar": "لَٰكِن",
        "root": "",
        "pos": "AMD",
        "word_type": "noun",
        "freq": 73,
    },
    "QCV-0251": {
        "lemma_ar": "صَٰلِحَٰت",
        "root": "ص ل ح",
        "pos": "N",
        "word_type": "noun",
        "freq": 62,
    },
    "QCV-0252": {
        "lemma_ar": "بَعَثَ",
        "root": "ب ع ث",
        "pos": "V",
        "word_type": "verb",
        "freq": 52,
    },
    "QCV-0257": {
        "lemma_ar": "اسْتَغْفَرَ",
        "root": "غ ف ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 40,
    },
    "QCV-0259": {
        "lemma_ar": "يَذَرَ",
        "root": "و ذ ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 45,
    },
    "QCV-0260": {
        "lemma_ar": "كَثِير",
        "root": "ك ث ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 63,
    },
    "QCV-0265": {
        "lemma_ar": "أَنذَرَ",
        "root": "ن ذ ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 44,
    },
    "QCV-0266": {
        "lemma_ar": "مَلَكَتْ",
        "root": "م ل ك",
        "pos": "V",
        "word_type": "verb",
        "freq": 44,
    },
    "QCV-0269": {
        "lemma_ar": "افْتَرَىٰ",
        "root": "ف ر ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 50,
    },
    "QCV-0273": {
        "lemma_ar": "شَدِيد",
        "root": "ش د د",
        "pos": "ADJ",
        "word_type": "adjective",
        "freq": 56,
    },
    "QCV-0275": {
        "lemma_ar": "أَرَيْ",
        "root": "ر ا ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 40,
    },
    "QCV-0276": {
        "lemma_ar": "بِئْسَ",
        "root": "ب ا س",
        "pos": "V",
        "word_type": "verb",
        "freq": 40,
    },
    "QCV-0281": {
        "lemma_ar": "مَاتَ",
        "root": "م و ت",
        "pos": "V",
        "word_type": "verb",
        "freq": 39,
    },
    "QCV-0284": {
        "lemma_ar": "نَهَار",
        "root": "ن ه ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 57,
    },
    "QCV-0285": {
        "lemma_ar": "اسْتَطَاعَ",
        "root": "ط و ع",
        "pos": "V",
        "word_type": "verb",
        "freq": 42,
    },
    "QCV-0287": {
        "lemma_ar": "نَذِير",
        "root": "ن ذ ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 58,
    },
    "QCV-0288": {
        "lemma_ar": "مُتَّقِين",
        "root": "و ق ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 49,
    },
    "QCV-0289": {
        "lemma_ar": "يَحْزُن",
        "root": "ح ز ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 37,
    },
    "QCV-0290": {
        "lemma_ar": "أُمَّة",
        "root": "ا م م",
        "pos": "N",
        "word_type": "noun",
        "freq": 64,
    },
    "QCV-0291": {
        "lemma_ar": "مُجْرِم",
        "root": "ج ر م",
        "pos": "N",
        "word_type": "noun",
        "freq": 52,
    },
    "QCV-0292": {
        "lemma_ar": "بُشِّرَ",
        "root": "ب ش ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 38,
    },
    "QCV-0293": {
        "lemma_ar": "حَمَلَ",
        "root": "ح م ل",
        "pos": "V",
        "word_type": "verb",
        "freq": 41,
    },
    "QCV-0294": {
        "lemma_ar": "اسْتَوَىٰٓ",
        "root": "س و ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 35,
    },
    "QCV-0295": {
        "lemma_ar": "ذَاقُ",
        "root": "ذ و ق",
        "pos": "V",
        "word_type": "verb",
        "freq": 36,
    },
    "QCV-0297": {
        "lemma_ar": "جَمِيع",
        "root": "ج م ع",
        "pos": "N",
        "word_type": "noun",
        "freq": 53,
    },
    "QCV-0299": {
        "lemma_ar": "عَذَّبَ",
        "root": "ع ذ ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 41,
    },
    "QCV-0300": {
        "lemma_ar": "خَشِىَ",
        "root": "خ ش ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 40,
    },
    "QCV-0302": {
        "lemma_ar": "غَيْب",
        "root": "غ ي ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 49,
    },
    "QCV-0304": {
        "lemma_ar": "بَلَغَ",
        "root": "ب ل غ",
        "pos": "V",
        "word_type": "verb",
        "freq": 40,
    },
    "QCV-0306": {
        "lemma_ar": "ابْتَغَىٰ",
        "root": "ب غ ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 34,
    },
    "QCV-0308": {
        "lemma_ar": "نَجَّىٰ",
        "root": "ن ج و",
        "pos": "V",
        "word_type": "verb",
        "freq": 37,
    },
    "QCV-0313": {
        "lemma_ar": "صَدَّ",
        "root": "ص د د",
        "pos": "V",
        "word_type": "verb",
        "freq": 37,
    },
    "QCV-0314": {
        "lemma_ar": "أَعْلَم",
        "root": "ع ل م",
        "pos": "N",
        "word_type": "noun",
        "freq": 49,
    },
    "QCV-0316": {
        "lemma_ar": "اخْتَلَفَ",
        "root": "خ ل ف",
        "pos": "V",
        "word_type": "verb",
        "freq": 35,
    },
    "QCV-0317": {
        "lemma_ar": "سَآءَ",
        "root": "س و ا",
        "pos": "V",
        "word_type": "verb",
        "freq": 30,
    },
    "QCV-0318": {
        "lemma_ar": "حَرَّمَ",
        "root": "ح ر م",
        "pos": "V",
        "word_type": "verb",
        "freq": 39,
    },
    "QCV-0320": {
        "lemma_ar": "مُسْتَقِيم",
        "root": "ق و م",
        "pos": "N",
        "word_type": "noun",
        "freq": 37,
    },
    "QCV-0322": {
        "lemma_ar": "سُوٓء",
        "root": "س و ا",
        "pos": "N",
        "word_type": "noun",
        "freq": 50,
    },
    "QCV-0324": {
        "lemma_ar": "سَجَدَ",
        "root": "س ج د",
        "pos": "V",
        "word_type": "verb",
        "freq": 35,
    },
    "QCV-0325": {
        "lemma_ar": "إِيمَٰن",
        "root": "ا م ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 45,
    },
    "QCV-0327": {
        "lemma_ar": "أُولِى",
        "root": "ا و ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 45,
    },
    "QCV-0328": {
        "lemma_ar": "حَمْد",
        "root": "ح م د",
        "pos": "N",
        "word_type": "noun",
        "freq": 43,
    },
    "QCV-0330": {
        "lemma_ar": "أَمَّا",
        "root": "",
        "pos": "EXL",
        "word_type": "noun",
        "freq": 55,
    },
    "QCV-0333": {
        "lemma_ar": "أَعْرَضَ",
        "root": "ع ر ض",
        "pos": "V",
        "word_type": "verb",
        "freq": 32,
    },
    "QCV-0335": {
        "lemma_ar": "أَبْصَرَ",
        "root": "ب ص ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 29,
    },
    "QCV-0336": {
        "lemma_ar": "أَغْنَتْ",
        "root": "غ ن ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 28,
    },
    "QCV-0337": {
        "lemma_ar": "سُبْحَٰن",
        "root": "س ب ح",
        "pos": "N",
        "word_type": "noun",
        "freq": 41,
    },
    "QCV-0340": {
        "lemma_ar": "ضَلَٰل",
        "root": "ض ل ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 38,
    },
    "QCV-0344": {
        "lemma_ar": "قَدَّمَ",
        "root": "ق د م",
        "pos": "V",
        "word_type": "verb",
        "freq": 27,
    },
    "QCV-0345": {
        "lemma_ar": "نَسِىَ",
        "root": "ن س ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 35,
    },
    "QCV-0347": {
        "lemma_ar": "نِسَآء",
        "root": "ن س و",
        "pos": "N",
        "word_type": "noun",
        "freq": 59,
    },
    "QCV-0349": {
        "lemma_ar": "صِرَٰط",
        "root": "ص ر ط",
        "pos": "N",
        "word_type": "noun",
        "freq": 45,
    },
    "QCV-0350": {
        "lemma_ar": "جَبَل",
        "root": "ج ب ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 39,
    },
    "QCV-0352": {
        "lemma_ar": "أَصْلَحَ",
        "root": "ص ل ح",
        "pos": "V",
        "word_type": "verb",
        "freq": 28,
    },
    "QCV-0353": {
        "lemma_ar": "أَصْبَحَ",
        "root": "ص ب ح",
        "pos": "V",
        "word_type": "verb",
        "freq": 28,
    },
    "QCV-0360": {
        "lemma_ar": "اسْم",
        "root": "س م و",
        "pos": "N",
        "word_type": "noun",
        "freq": 39,
    },
    "QCV-0361": {
        "lemma_ar": "أَحْسَن",
        "root": "ح س ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 36,
    },
    "QCV-0362": {
        "lemma_ar": "زَيَّنَ",
        "root": "ز ي ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 26,
    },
    "QCV-0363": {
        "lemma_ar": "كَفَىٰ",
        "root": "ك ف ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 32,
    },
    "QCV-0364": {
        "lemma_ar": "اسْتَجَابَ",
        "root": "ج و ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 28,
    },
    "QCV-0367": {
        "lemma_ar": "سَيِّـَٔات",
        "root": "س و ا",
        "pos": "N",
        "word_type": "noun",
        "freq": 36,
    },
    "QCV-0369": {
        "lemma_ar": "عَسَى",
        "root": "ع س ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 30,
    },
    "QCV-0370": {
        "lemma_ar": "وَيْل",
        "root": "",
        "pos": "N",
        "word_type": "noun",
        "freq": 40,
    },
    "QCV-0371": {
        "lemma_ar": "مَيِّت",
        "root": "م و ت",
        "pos": "N",
        "word_type": "noun",
        "freq": 38,
    },
    "QCV-0372": {
        "lemma_ar": "لَبِثَ",
        "root": "ل ب ث",
        "pos": "V",
        "word_type": "verb",
        "freq": 30,
    },
    "QCV-0375": {
        "lemma_ar": "سُلْطَٰن",
        "root": "س ل ط",
        "pos": "N",
        "word_type": "noun",
        "freq": 37,
    },
    "QCV-0376": {
        "lemma_ar": "تَوَفَّىٰ",
        "root": "و ف ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 24,
    },
    "QCV-0381": {
        "lemma_ar": "جَٰهَدَ",
        "root": "ج ه د",
        "pos": "V",
        "word_type": "verb",
        "freq": 27,
    },
    "QCV-0382": {
        "lemma_ar": "نَعَم",
        "root": "ن ع م",
        "pos": "N",
        "word_type": "noun",
        "freq": 33,
    },
    "QCV-0383": {
        "lemma_ar": "خَلَا",
        "root": "خ ل و",
        "pos": "V",
        "word_type": "verb",
        "freq": 25,
    },
    "QCV-0384": {
        "lemma_ar": "كَادَ",
        "root": "ك و د",
        "pos": "V",
        "word_type": "verb",
        "freq": 24,
    },
    "QCV-0385": {
        "lemma_ar": "يَشْعُرُ",
        "root": "ش ع ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 25,
    },
    "QCV-0386": {
        "lemma_ar": "إِسْرَائِيل",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 43,
    },
    "QCV-0387": {
        "lemma_ar": "شَرِيك",
        "root": "ش ر ك",
        "pos": "N",
        "word_type": "noun",
        "freq": 40,
    },
    "QCV-0391": {
        "lemma_ar": "فَتَنُ",
        "root": "ف ت ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 23,
    },
    "QCV-0392": {
        "lemma_ar": "فَاسِق",
        "root": "ف س ق",
        "pos": "N",
        "word_type": "noun",
        "freq": 37,
    },
    "QCV-0393": {
        "lemma_ar": "مَتَٰع",
        "root": "م ت ع",
        "pos": "N",
        "word_type": "noun",
        "freq": 35,
    },
    "QCV-0397": {
        "lemma_ar": "عَٰقِبَة",
        "root": "ع ق ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 32,
    },
    "QCV-0398": {
        "lemma_ar": "جَٰدَلُ",
        "root": "ج د ل",
        "pos": "V",
        "word_type": "verb",
        "freq": 25,
    },
    "QCV-0399": {
        "lemma_ar": "رَفَعَ",
        "root": "ر ف ع",
        "pos": "V",
        "word_type": "verb",
        "freq": 22,
    },
    "QCV-0402": {
        "lemma_ar": "أَسْلَمَ",
        "root": "س ل م",
        "pos": "V",
        "word_type": "verb",
        "freq": 22,
    },
    "QCV-0403": {
        "lemma_ar": "زَكَوٰة",
        "root": "ز ك و",
        "pos": "N",
        "word_type": "noun",
        "freq": 32,
    },
    "QCV-0404": {
        "lemma_ar": "وَٰحِدَة",
        "root": "و ح د",
        "pos": "N",
        "word_type": "noun",
        "freq": 31,
    },
    "QCV-0405": {
        "lemma_ar": "نَصِير",
        "root": "ن ص ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 35,
    },
    "QCV-0407": {
        "lemma_ar": "يَرْجُوا@",
        "root": "ر ج و",
        "pos": "V",
        "word_type": "verb",
        "freq": 22,
    },
    "QCV-0408": {
        "lemma_ar": "مُرْسَل",
        "root": "ر س ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 35,
    },
    "QCV-0409": {
        "lemma_ar": "فَرِيق",
        "root": "ف ر ق",
        "pos": "N",
        "word_type": "noun",
        "freq": 33,
    },
    "QCV-0410": {
        "lemma_ar": "أَذَاقَ",
        "root": "ذ و ق",
        "pos": "V",
        "word_type": "verb",
        "freq": 22,
    },
    "QCV-0411": {
        "lemma_ar": "خَٰسِرِين",
        "root": "خ س ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 32,
    },
    "QCV-0412": {
        "lemma_ar": "وَٰحِد",
        "root": "و ح د",
        "pos": "ADJ",
        "word_type": "adjective",
        "freq": 30,
    },
    "QCV-0413": {
        "lemma_ar": "سَوَآء",
        "root": "س و ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 27,
    },
    "QCV-0414": {
        "lemma_ar": "وَهَبَ",
        "root": "و ه ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 22,
    },
    "QCV-0415": {
        "lemma_ar": "اسْتُهْزِئَ",
        "root": "ه ز ا",
        "pos": "V",
        "word_type": "verb",
        "freq": 21,
    },
    "QCV-0416": {
        "lemma_ar": "مَعْرُوف",
        "root": "ع ر ف",
        "pos": "N",
        "word_type": "noun",
        "freq": 38,
    },
    "QCV-0417": {
        "lemma_ar": "لَعَنَ",
        "root": "ل ع ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 23,
    },
    "QCV-0420": {
        "lemma_ar": "أَكْبَر",
        "root": "ك ب ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0422": {
        "lemma_ar": "سَخَّرَ",
        "root": "س خ ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 22,
    },
    "QCV-0423": {
        "lemma_ar": "وَضَعَ",
        "root": "و ض ع",
        "pos": "V",
        "word_type": "verb",
        "freq": 21,
    },
    "QCV-0424": {
        "lemma_ar": "أَشَدّ",
        "root": "ش د د",
        "pos": "N",
        "word_type": "noun",
        "freq": 31,
    },
    "QCV-0427": {
        "lemma_ar": "مَشَ",
        "root": "م ش ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 21,
    },
    "QCV-0429": {
        "lemma_ar": "كَلِمَة",
        "root": "ك ل م",
        "pos": "N",
        "word_type": "noun",
        "freq": 28,
    },
    "QCV-0432": {
        "lemma_ar": "مَصِير",
        "root": "ص ي ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 28,
    },
    "QCV-0433": {
        "lemma_ar": "حَدِيث",
        "root": "ح د ث",
        "pos": "N",
        "word_type": "noun",
        "freq": 28,
    },
    "QCV-0434": {
        "lemma_ar": "يَضُرَّ",
        "root": "ض ر ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 19,
    },
    "QCV-0438": {
        "lemma_ar": "كَلَّمَ",
        "root": "ك ل م",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0439": {
        "lemma_ar": "تَعَٰلَىٰ",
        "root": "ع ل و",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0441": {
        "lemma_ar": "أَجْمَعِين",
        "root": "ج م ع",
        "pos": "N",
        "word_type": "noun",
        "freq": 26,
    },
    "QCV-0446": {
        "lemma_ar": "بَلَوْ",
        "root": "ب ل و",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0450": {
        "lemma_ar": "اشْتَرَىٰ",
        "root": "ش ر ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 21,
    },
    "QCV-0451": {
        "lemma_ar": "أَقْسَمُ",
        "root": "ق س م",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0453": {
        "lemma_ar": "بَٰطِل",
        "root": "ب ط ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 26,
    },
    "QCV-0455": {
        "lemma_ar": "سَبَقَ",
        "root": "س ب ق",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0456": {
        "lemma_ar": "نَفَخَ",
        "root": "ن ف خ",
        "pos": "V",
        "word_type": "verb",
        "freq": 19,
    },
    "QCV-0457": {
        "lemma_ar": "رِجَال",
        "root": "ر ج ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 28,
    },
    "QCV-0458": {
        "lemma_ar": "ءَال",
        "root": "ا و ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 26,
    },
    "QCV-0460": {
        "lemma_ar": "كَتَمَ",
        "root": "ك ت م",
        "pos": "V",
        "word_type": "verb",
        "freq": 21,
    },
    "QCV-0461": {
        "lemma_ar": "اسْتَعْجَلَ",
        "root": "ع ج ل",
        "pos": "V",
        "word_type": "verb",
        "freq": 19,
    },
    "QCV-0462": {
        "lemma_ar": "اسْتَمَعَ",
        "root": "س م ع",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0465": {
        "lemma_ar": "عَاد2",
        "root": "ع و د",
        "pos": "PN",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0466": {
        "lemma_ar": "عَرَفَ",
        "root": "ع ر ف",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0468": {
        "lemma_ar": "أُعِيدُ",
        "root": "ع و د",
        "pos": "V",
        "word_type": "verb",
        "freq": 18,
    },
    "QCV-0469": {
        "lemma_ar": "أَنْعَمَ",
        "root": "ن ع م",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0471": {
        "lemma_ar": "مَلَأ",
        "root": "م ل ا",
        "pos": "N",
        "word_type": "noun",
        "freq": 30,
    },
    "QCV-0472": {
        "lemma_ar": "حَيْث",
        "root": "ح ي ث",
        "pos": "N",
        "word_type": "noun",
        "freq": 29,
    },
    "QCV-0473": {
        "lemma_ar": "أَبَدًا",
        "root": "ا ب د",
        "pos": "T",
        "word_type": "noun",
        "freq": 28,
    },
    "QCV-0474": {
        "lemma_ar": "غَٰفِل",
        "root": "غ ف ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 27,
    },
    "QCV-0477": {
        "lemma_ar": "ذِكْرَىٰ",
        "root": "ذ ك ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 23,
    },
    "QCV-0479": {
        "lemma_ar": "أَحَلَّ",
        "root": "ح ل ل",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0480": {
        "lemma_ar": "وَفَّىٰٓ",
        "root": "و ف ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 18,
    },
    "QCV-0483": {
        "lemma_ar": "شَهَٰدَة",
        "root": "ش ه د",
        "pos": "N",
        "word_type": "noun",
        "freq": 23,
    },
    "QCV-0484": {
        "lemma_ar": "شَاهِد",
        "root": "ش ه د",
        "pos": "N",
        "word_type": "noun",
        "freq": 21,
    },
    "QCV-0485": {
        "lemma_ar": "أَعَدَّ",
        "root": "ع د د",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0486": {
        "lemma_ar": "أَنشَأَ",
        "root": "ن ش ا",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0487": {
        "lemma_ar": "عَهْد",
        "root": "ع ه د",
        "pos": "N",
        "word_type": "noun",
        "freq": 29,
    },
    "QCV-0488": {
        "lemma_ar": "مَكَان",
        "root": "ك و ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 27,
    },
    "QCV-0493": {
        "lemma_ar": "مُؤْمِنَٰت",
        "root": "ا م ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 22,
    },
    "QCV-0494": {
        "lemma_ar": "يَفْقَهُ",
        "root": "ف ق ه",
        "pos": "V",
        "word_type": "verb",
        "freq": 19,
    },
    "QCV-0495": {
        "lemma_ar": "تَبَيَّنَ",
        "root": "ب ي ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 18,
    },
    "QCV-0496": {
        "lemma_ar": "قَصَّ",
        "root": "ق ص ص",
        "pos": "V",
        "word_type": "verb",
        "freq": 20,
    },
    "QCV-0499": {
        "lemma_ar": "أَمْسَكَ",
        "root": "م س ك",
        "pos": "V",
        "word_type": "verb",
        "freq": 18,
    },
    "QCV-0501": {
        "lemma_ar": "ءَالَآء",
        "root": "ا ل و",
        "pos": "N",
        "word_type": "noun",
        "freq": 34,
    },
    "QCV-0503": {
        "lemma_ar": "امْرَأَت",
        "root": "م ر ا",
        "pos": "N",
        "word_type": "noun",
        "freq": 26,
    },
    "QCV-0504": {
        "lemma_ar": "طَعَام",
        "root": "ط ع م",
        "pos": "N",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0505": {
        "lemma_ar": "لِقَآء",
        "root": "ل ق ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0506": {
        "lemma_ar": "وَدَّ",
        "root": "و د د",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0507": {
        "lemma_ar": "يَتَفَكَّرُ",
        "root": "ف ك ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0509": {
        "lemma_ar": "ظُلُمَٰت",
        "root": "ظ ل م",
        "pos": "N",
        "word_type": "noun",
        "freq": 23,
    },
    "QCV-0512": {
        "lemma_ar": "أُغْرِقُ",
        "root": "غ ر ق",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0513": {
        "lemma_ar": "أَدْرَىٰ",
        "root": "د ر ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0515": {
        "lemma_ar": "مُسَمًّى",
        "root": "س م و",
        "pos": "N",
        "word_type": "noun",
        "freq": 21,
    },
    "QCV-0516": {
        "lemma_ar": "مُنَٰفِقُون",
        "root": "ن ف ق",
        "pos": "N",
        "word_type": "noun",
        "freq": 27,
    },
    "QCV-0517": {
        "lemma_ar": "دُعَآء",
        "root": "د ع و",
        "pos": "N",
        "word_type": "noun",
        "freq": 22,
    },
    "QCV-0519": {
        "lemma_ar": "انقَلَبَ",
        "root": "ق ل ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0520": {
        "lemma_ar": "وَقَىٰ",
        "root": "و ق ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0523": {
        "lemma_ar": "أُنثَىٰ",
        "root": "ا ن ث",
        "pos": "N",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0524": {
        "lemma_ar": "قَرْن",
        "root": "ق ر ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 23,
    },
    "QCV-0525": {
        "lemma_ar": "أَن[بَتَ",
        "root": "ن ب ت",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0526": {
        "lemma_ar": "سَارَ",
        "root": "س ي ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0527": {
        "lemma_ar": "إِيَّا",
        "root": "",
        "pos": "PRON",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0530": {
        "lemma_ar": "انتَهَىٰ",
        "root": "ن ه ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0531": {
        "lemma_ar": "سَكَنَ",
        "root": "س ك ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0532": {
        "lemma_ar": "طَآئِفَة",
        "root": "ط و ف",
        "pos": "N",
        "word_type": "noun",
        "freq": 24,
    },
    "QCV-0533": {
        "lemma_ar": "ذَا",
        "root": "",
        "pos": "N",
        "word_type": "noun",
        "freq": 23,
    },
    "QCV-0535": {
        "lemma_ar": "عِيسَى",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 25,
    },
    "QCV-0541": {
        "lemma_ar": "أَحَاطَ",
        "root": "ح و ط",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0542": {
        "lemma_ar": "فَصَّلَ",
        "root": "ف ص ل",
        "pos": "V",
        "word_type": "verb",
        "freq": 17,
    },
    "QCV-0544": {
        "lemma_ar": "بَسَطَ",
        "root": "ب س ط",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0545": {
        "lemma_ar": "قَرَأَ",
        "root": "ق ر ا",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0546": {
        "lemma_ar": "أَفْسَدُ",
        "root": "ف س د",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0547": {
        "lemma_ar": "آدَم",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 25,
    },
    "QCV-0548": {
        "lemma_ar": "أَتَمَّ",
        "root": "ت م م",
        "pos": "V",
        "word_type": "verb",
        "freq": 16,
    },
    "QCV-0549": {
        "lemma_ar": "وَعَظْ",
        "root": "و ع ظ",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0550": {
        "lemma_ar": "طَيِّبَٰت",
        "root": "ط ي ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 21,
    },
    "QCV-0551": {
        "lemma_ar": "قَآئِم",
        "root": "ق و م",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0552": {
        "lemma_ar": "لَقُ",
        "root": "ل ق ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 14,
    },
    "QCV-0553": {
        "lemma_ar": "مِيثَٰق",
        "root": "و ث ق",
        "pos": "N",
        "word_type": "noun",
        "freq": 25,
    },
    "QCV-0555": {
        "lemma_ar": "أَعْمَىٰ",
        "root": "ع م ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 21,
    },
    "QCV-0558": {
        "lemma_ar": "سَبْع",
        "root": "س ب ع",
        "pos": "N",
        "word_type": "noun",
        "freq": 23,
    },
    "QCV-0559": {
        "lemma_ar": "مُكَذِّبِين",
        "root": "ك ذ ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 21,
    },
    "QCV-0561": {
        "lemma_ar": "غَلَبُ",
        "root": "غ ل ب",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0562": {
        "lemma_ar": "مَدَّ",
        "root": "م د د",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0563": {
        "lemma_ar": "سَوَّىٰ",
        "root": "س و ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0565": {
        "lemma_ar": "جُنَاح",
        "root": "ج ن ح",
        "pos": "N",
        "word_type": "noun",
        "freq": 25,
    },
    "QCV-0568": {
        "lemma_ar": "يُبْدِىَ",
        "root": "ب د و",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0569": {
        "lemma_ar": "غَرَّ",
        "root": "غ ر ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0571": {
        "lemma_ar": "صَرَفَ",
        "root": "ص ر ف",
        "pos": "V",
        "word_type": "verb",
        "freq": 14,
    },
    "QCV-0572": {
        "lemma_ar": "كَشَفَ",
        "root": "ك ش ف",
        "pos": "V",
        "word_type": "verb",
        "freq": 14,
    },
    "QCV-0573": {
        "lemma_ar": "أَسْمَعَ",
        "root": "س م ع",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0574": {
        "lemma_ar": "أَقْرَب",
        "root": "ق ر ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0575": {
        "lemma_ar": "حُسْنَىٰ",
        "root": "ح س ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0576": {
        "lemma_ar": "حَلَلْ",
        "root": "ح ل ل",
        "pos": "V",
        "word_type": "verb",
        "freq": 14,
    },
    "QCV-0577": {
        "lemma_ar": "يَصْلَى",
        "root": "ص ل ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0578": {
        "lemma_ar": "أُوذِىَ",
        "root": "ا ذ ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0579": {
        "lemma_ar": "أَعْتَدَتْ",
        "root": "ع ت د",
        "pos": "V",
        "word_type": "verb",
        "freq": 14,
    },
    "QCV-0581": {
        "lemma_ar": "اعْتَدَىٰ",
        "root": "ع د و",
        "pos": "V",
        "word_type": "verb",
        "freq": 15,
    },
    "QCV-0582": {
        "lemma_ar": "مُعْرِضُون",
        "root": "ع ر ض",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0583": {
        "lemma_ar": "فَوْز",
        "root": "ف و ز",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0586": {
        "lemma_ar": "يُنظَرُ",
        "root": "ن ظ ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0587": {
        "lemma_ar": "نَصِيب",
        "root": "ن ص ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 21,
    },
    "QCV-0590": {
        "lemma_ar": "تَقْوَى",
        "root": "و ق ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0592": {
        "lemma_ar": "نَكَحَ",
        "root": "ن ك ح",
        "pos": "V",
        "word_type": "verb",
        "freq": 14,
    },
    "QCV-0593": {
        "lemma_ar": "قُطِعَ",
        "root": "ق ط ع",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0595": {
        "lemma_ar": "غَشِيَ",
        "root": "غ ش و",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0596": {
        "lemma_ar": "أَطْعَمَ",
        "root": "ط ع م",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0598": {
        "lemma_ar": "يُوقِنُ",
        "root": "ي ق ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0600": {
        "lemma_ar": "هَٰرُون",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 20,
    },
    "QCV-0601": {
        "lemma_ar": "شَجَرَة",
        "root": "ش ج ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0602": {
        "lemma_ar": "ضُرّ",
        "root": "ض ر ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0603": {
        "lemma_ar": "قُرْبَىٰ",
        "root": "ق ر ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 16,
    },
    "QCV-0605": {
        "lemma_ar": "رَيْب",
        "root": "ر ي ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0607": {
        "lemma_ar": "أَبَى",
        "root": "ا ب ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0608": {
        "lemma_ar": "زَعَمَ",
        "root": "ز ع م",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0609": {
        "lemma_ar": "يَصِفُ",
        "root": "و ص ف",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0611": {
        "lemma_ar": "حَبِطَ",
        "root": "ح ب ط",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0612": {
        "lemma_ar": "مُصَدِّق",
        "root": "ص د ق",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0613": {
        "lemma_ar": "مُهْتَدُون",
        "root": "ه د ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0615": {
        "lemma_ar": "اصْطَفَىٰ",
        "root": "ص ف و",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0616": {
        "lemma_ar": "يَحْذَرُ",
        "root": "ح ذ ر",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0617": {
        "lemma_ar": "قَعَدَ",
        "root": "ق ع د",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0618": {
        "lemma_ar": "أَخْزَيْ",
        "root": "خ ز ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0619": {
        "lemma_ar": "لَدَي",
        "root": "",
        "pos": "LOC",
        "word_type": "noun",
        "freq": 20,
    },
    "QCV-0620": {
        "lemma_ar": "حِزْب",
        "root": "ح ز ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 20,
    },
    "QCV-0621": {
        "lemma_ar": "تُرَاب",
        "root": "ت ر ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0623": {
        "lemma_ar": "مَكَّ",
        "root": "م ك ن",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0626": {
        "lemma_ar": "زِينَة",
        "root": "ز ي ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0628": {
        "lemma_ar": "دَرَجَة",
        "root": "د ر ج",
        "pos": "N",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0631": {
        "lemma_ar": "تَنزِيل",
        "root": "ن ز ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0632": {
        "lemma_ar": "تَرَبَّصْ",
        "root": "ر ب ص",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0633": {
        "lemma_ar": "وَرِثَ",
        "root": "و ر ث",
        "pos": "V",
        "word_type": "verb",
        "freq": 13,
    },
    "QCV-0635": {
        "lemma_ar": "سَقَىٰ",
        "root": "س ق ي",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0636": {
        "lemma_ar": "دُبُر",
        "root": "د ب ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0639": {
        "lemma_ar": "مَرَّة",
        "root": "م ر ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 19,
    },
    "QCV-0640": {
        "lemma_ar": "مَوْلَىٰ",
        "root": "و ل ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0641": {
        "lemma_ar": "حَآجَّ",
        "root": "ح ج ج",
        "pos": "V",
        "word_type": "verb",
        "freq": 12,
    },
    "QCV-0642": {
        "lemma_ar": "مُنكَر",
        "root": "ن ك ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0643": {
        "lemma_ar": "أَهْوَآء",
        "root": "ه و ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0646": {
        "lemma_ar": "تَأْوِيل",
        "root": "ا و ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0647": {
        "lemma_ar": "مُنذِر",
        "root": "ن ذ ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0651": {
        "lemma_ar": "فَٰحِشَة",
        "root": "ف ح ش",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0652": {
        "lemma_ar": "يَسِير",
        "root": "ي س ر",
        "pos": "ADJ",
        "word_type": "adjective",
        "freq": 15,
    },
    "QCV-0653": {
        "lemma_ar": "لَدُن",
        "root": "ل د ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0655": {
        "lemma_ar": "بُشْرَىٰ",
        "root": "ب ش ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0656": {
        "lemma_ar": "فُؤَاد",
        "root": "ف ا د",
        "pos": "N",
        "word_type": "noun",
        "freq": 16,
    },
    "QCV-0657": {
        "lemma_ar": "ثَمَرَٰت",
        "root": "ث م ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 16,
    },
    "QCV-0658": {
        "lemma_ar": "مَرْجِع",
        "root": "ر ج ع",
        "pos": "N",
        "word_type": "noun",
        "freq": 16,
    },
    "QCV-0659": {
        "lemma_ar": "بَنَات",
        "root": "ب ن ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0661": {
        "lemma_ar": "كُلَّمَا",
        "root": "ك ل ل",
        "pos": "T",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0665": {
        "lemma_ar": "تَوْرَىٰة",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 18,
    },
    "QCV-0667": {
        "lemma_ar": "أَلْبَٰب",
        "root": "ل ب ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 16,
    },
    "QCV-0670": {
        "lemma_ar": "دَاوُد",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 16,
    },
    "QCV-0674": {
        "lemma_ar": "سُلَيْمَٰن",
        "root": "",
        "pos": "PN",
        "word_type": "noun",
        "freq": 17,
    },
    "QCV-0676": {
        "lemma_ar": "مِلَّة",
        "root": "م ل ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0678": {
        "lemma_ar": "كَلِمَٰت",
        "root": "ك ل م",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0679": {
        "lemma_ar": "ابْتِغَآء",
        "root": "ب غ ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0681": {
        "lemma_ar": "لَعْنَة",
        "root": "ل ع ن",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0682": {
        "lemma_ar": "مُهِين",
        "root": "ه و ن",
        "pos": "ADJ",
        "word_type": "adjective",
        "freq": 14,
    },
    "QCV-0684": {
        "lemma_ar": "نَصْرَانِيّ",
        "root": "ن ص ر",
        "pos": "PN",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0685": {
        "lemma_ar": "مُفْلِحُون",
        "root": "ف ل ح",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0689": {
        "lemma_ar": "ظِلّ",
        "root": "ظ ل ل",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0690": {
        "lemma_ar": "أَثَر",
        "root": "ا ث ر",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0697": {
        "lemma_ar": "إِذَا2",
        "root": "",
        "pos": "SUR",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0699": {
        "lemma_ar": "أَدْنَىٰ",
        "root": "د ن و",
        "pos": "N",
        "word_type": "noun",
        "freq": 12,
    },
    "QCV-0701": {
        "lemma_ar": "غَالِب",
        "root": "غ ل ب",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0702": {
        "lemma_ar": "أَلْف",
        "root": "ا ل ف",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0705": {
        "lemma_ar": "حَرَج",
        "root": "ح ر ج",
        "pos": "N",
        "word_type": "noun",
        "freq": 15,
    },
    "QCV-0706": {
        "lemma_ar": "ثَلَٰثَة",
        "root": "ث ل ث",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0707": {
        "lemma_ar": "رِضْوَٰن",
        "root": "ر ض و",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0708": {
        "lemma_ar": "بَغْتَة",
        "root": "ب غ ت",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0713": {
        "lemma_ar": "مَثْوًى",
        "root": "ث و ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0717": {
        "lemma_ar": "شَفَٰعَة",
        "root": "ش ف ع",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0718": {
        "lemma_ar": "غُلَٰم",
        "root": "غ ل م",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0722": {
        "lemma_ar": "أَصَمّ",
        "root": "ص م م",
        "pos": "N",
        "word_type": "noun",
        "freq": 12,
    },
    "QCV-0727": {
        "lemma_ar": "حَنِيف",
        "root": "ح ن ف",
        "pos": "N",
        "word_type": "noun",
        "freq": 12,
    },
    "QCV-0728": {
        "lemma_ar": "أَفْوَٰه",
        "root": "ف و ه",
        "pos": "N",
        "word_type": "noun",
        "freq": 12,
    },
    "QCV-0731": {
        "lemma_ar": "اثْنَيْن",
        "root": "ث ن ي",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-0736": {
        "lemma_ar": "حُدُود",
        "root": "ح د د",
        "pos": "N",
        "word_type": "noun",
        "freq": 14,
    },
    "QCV-0743": {
        "lemma_ar": "حَرْث",
        "root": "ح ر ث",
        "pos": "N",
        "word_type": "noun",
        "freq": 13,
    },
    "QCV-1475": {
        "lemma_ar": "جَعْفَرٌ",
        "root": "",
        "pos": "N",
        "word_type": "noun",
        "freq": 5,
    },
    "QCV-1492": {
        "lemma_ar": "صُهَيْبٌ",
        "root": "",
        "pos": "N",
        "word_type": "noun",
        "freq": 5,
    },
    "QCV-1499": {
        "lemma_ar": "كَعْبٌ",
        "root": "",
        "pos": "N",
        "word_type": "noun",
        "freq": 5,
    },
    "QCV-1741": {
        "lemma_ar": "حُطَمَةٍ",
        "root": "ح ط م",
        "pos": "N",
        "word_type": "noun",
        "freq": 2,
    },
    "QCV-1791": {
        "lemma_ar": "سَعْدٌ",
        "root": "س ع د",
        "pos": "V",
        "word_type": "verb",
        "freq": 1,
    },
    "QCV-1963": {
        "lemma_ar": "جِبْتٍ",
        "root": "ج ب ت",
        "pos": "N",
        "word_type": "noun",
        "freq": 1,
    },
    "QCV-1970": {
        "lemma_ar": "زَيْدٌ",
        "root": "",
        "pos": "PN",
        "word_type": "proper_noun",
        "freq": 1,
    },
}
